#Jekyll
title:          Total Possession Soccer
name:
url:
destination:    ../dist
permalink:      "/:slug/"
year:           2016

#Assets
sass:
    sass_dir:   _sass
    style:      :compressed

#Include
include:        ['_pages']

#Exclude
exclude:        ['js/bootstrap/', 'js/scripts/', 'js/jekyll-bootstrap.js', 'js/bootstrap.js']
